import { Lead, Demo, Proposal, Client, Campaign, PaymentInvoice, ProductPackage } from './types';

export const mockUsers = [
  { id: '1', name: 'Sujan Karki', role: 'Marketing Executive', email: 'sujan@nagarik.com', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256' },
  { id: '2', name: 'Anita Sharma', role: 'Sales Manager', email: 'anita@nagarik.com', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=256' },
  { id: '3', name: 'Bikram Raut', role: 'Business Developer', email: 'bikram@nagarik.com', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=256' },
  { id: '4', name: 'Pooja Mahat', role: 'Customer Relations', email: 'pooja@nagarik.com', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=256' },
  { id: '5', name: 'Ramesh Thapa', role: 'Account Executive', email: 'ramesh@nagarik.com', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=256' }
];

export const initialWebsiteLeads: Lead[] = [
  {
    id: 'W-001',
    businessName: 'Himalayan Coffee House',
    city: 'Thamel, Kathmandu',
    contactPerson: 'Nirajan Shrestha',
    contactRole: 'Owner',
    phone: '9851122334',
    email: 'nirajan@himalayancoffee.com',
    category: 'Hospitality',
    websiteStatus: 'No Website',
    suggestedPitch: 'Get a professional website to build trust and visibility.',
    packageOffered: 'Starter Website\n(NPR 9,999)',
    leadPriority: 'Hot',
    followUpStatus: 'Follow-up Required',
    nextFollowUpDate: '20 May 2025',
    followUpDelayText: 'In 2 days',
    clientResponse: 'Interested',
    assignedTo: 'Sujan Karki',
    remarks: 'Wants website with booking form',
    leadSource: 'Website',
    productsInterestedText: 'Starter Website'
  },
  {
    id: 'W-002',
    businessName: 'Everest Yoga Studio',
    city: 'Lazimpat, Kathmandu',
    contactPerson: 'Pranita Gurung',
    contactRole: 'Studio Manager',
    phone: '9848877665',
    email: 'pranita@everestyoga.com',
    category: 'Retail',
    websiteStatus: 'Old Website',
    suggestedPitch: 'Redesign to modern, mobile-friendly website.',
    packageOffered: 'Business Website\n(NPR 19,999)',
    leadPriority: 'Warm',
    followUpStatus: 'Proposal Sent',
    nextFollowUpDate: '22 May 2025',
    followUpDelayText: 'In 4 days',
    clientResponse: 'Under Review',
    assignedTo: 'Anita Sharma',
    remarks: 'Will decide after team review',
    leadSource: 'Google Maps',
    productsInterestedText: 'Business Website'
  },
  {
    id: 'W-003',
    businessName: 'Green Valley Organics',
    city: 'Kupandole, Lalitpur',
    contactPerson: 'Ramesh Adhikari',
    contactRole: 'Director',
    phone: '9812345678',
    email: 'ramesh@greenvalley.com',
    category: 'Trading',
    websiteStatus: 'Needs Redesign',
    suggestedPitch: 'Ecommerce website to grow online sales.',
    packageOffered: 'Ecommerce Website\n(NPR 39,999)',
    leadPriority: 'Hot',
    followUpStatus: 'Follow-up Required',
    nextFollowUpDate: '21 May 2025',
    followUpDelayText: 'In 3 days',
    clientResponse: 'Interested',
    assignedTo: 'Bikram Raut',
    remarks: 'Needs payment gateway',
    leadSource: 'Facebook',
    productsInterestedText: 'Ecommerce Website'
  },
  {
    id: 'W-004',
    businessName: 'Kathmandu Pet Care',
    city: 'Maharajgunj, Kathmandu',
    contactPerson: 'Sunita Joshi',
    contactRole: 'Director',
    phone: '9856677889',
    email: 'sunita@ktmpetcare.com',
    category: 'Healthcare',
    websiteStatus: 'Business Website',
    suggestedPitch: 'Add online booking and service pages.',
    packageOffered: 'Business Website\n(NPR 19,999)',
    leadPriority: 'Warm',
    followUpStatus: 'Interested',
    nextFollowUpDate: '23 May 2025',
    followUpDelayText: 'In 5 days',
    clientResponse: 'Interested',
    assignedTo: 'Ramesh Thapa',
    remarks: 'Looking for booking system',
    leadSource: 'Referral',
    productsInterestedText: 'Business Website'
  },
  {
    id: 'W-005',
    businessName: 'BuyNepal Online Mart',
    city: 'New Baneshwor, KTM',
    contactPerson: 'Binod Shrestha',
    contactRole: 'Founder',
    phone: '9801122335',
    email: 'binod@buynepal.com',
    category: 'Trading',
    websiteStatus: 'Ecommerce Website',
    suggestedPitch: 'Upgrade & add new features for growth.',
    packageOffered: "Ecommerce Website\n(Advanced)\n(NPR 59,999)",
    leadPriority: 'Hot',
    followUpStatus: 'Proposal Sent',
    nextFollowUpDate: '19 May 2025',
    followUpDelayText: 'Tomorrow',
    clientResponse: 'Very Interested',
    assignedTo: 'Sujan Karki',
    remarks: 'High potential client',
    leadSource: 'Website',
    productsInterestedText: 'Advanced Ecommerce'
  },
  {
    id: 'W-006',
    businessName: 'The Himalayan Times',
    city: 'Dillibazar, Kathmandu',
    contactPerson: 'Karan Malla',
    contactRole: 'IT Head',
    phone: '9841555677',
    email: 'karan@himalayantimes.com',
    category: 'IT Services',
    websiteStatus: 'Needs Redesign',
    suggestedPitch: 'News website with better performance.',
    packageOffered: 'Business Website\n(NPR 19,999)',
    leadPriority: 'Warm',
    followUpStatus: 'Follow-up Required',
    nextFollowUpDate: '24 May 2025',
    followUpDelayText: 'In 6 days',
    clientResponse: 'Interested',
    assignedTo: 'Anita Sharma',
    remarks: 'Needs content migration',
    leadSource: 'Google Maps',
    productsInterestedText: 'Business Website'
  },
  {
    id: 'W-007',
    businessName: 'Decor & More Interiors',
    city: 'Kuleshwor, Kathmandu',
    contactPerson: 'Sushil Shakya',
    contactRole: 'Managing Director',
    phone: '9853322110',
    email: 'sushil@decorandmore.com',
    category: 'Trading',
    websiteStatus: 'No Website',
    suggestedPitch: 'Showcase portfolio and attract leads.',
    packageOffered: 'Starter Website\n(NPR 9,999)',
    leadPriority: 'Warm',
    followUpStatus: 'Not Contacted',
    nextFollowUpDate: '26 May 2025',
    followUpDelayText: 'In 8 days',
    clientResponse: 'Not Yet Contacted',
    assignedTo: 'Pooja Mahat',
    remarks: 'Wants modern portfolio site',
    leadSource: 'Referral',
    productsInterestedText: 'Starter Website'
  },
  {
    id: 'W-008',
    businessName: 'Pure Herbs Nepal',
    city: 'Balaju, Kathmandu',
    contactPerson: 'Resham Tamang',
    contactRole: 'Marketing Manager',
    phone: '9869908877',
    email: 'resham@pureherbs.com',
    category: 'Trading',
    websiteStatus: 'Old Website',
    suggestedPitch: 'Redesign with SEO and speed boost.',
    packageOffered: 'Business Website\n(NPR 19,999)',
    leadPriority: 'Warm',
    followUpStatus: 'Interested',
    nextFollowUpDate: '20 May 2025',
    followUpDelayText: 'In 2 days',
    clientResponse: 'Interested',
    assignedTo: 'Bikram Raut',
    remarks: 'Budget approved',
    leadSource: 'Instagram',
    productsInterestedText: 'Business Website'
  },
  {
    id: 'W-009',
    businessName: 'Pokhara Adventure Co.',
    city: 'Lakeside, Pokhara',
    contactPerson: 'Tashi Gurung',
    contactRole: 'Operations Head',
    phone: '9856044332',
    email: 'tashi@pokharaadventure.com',
    category: 'Hospitality',
    websiteStatus: 'Needs Redesign',
    suggestedPitch: 'Travel website with booking functionality.',
    packageOffered: 'Ecommerce Website\n(NPR 39,999)',
    leadPriority: 'Hot',
    followUpStatus: 'Follow-up Required',
    nextFollowUpDate: '22 May 2025',
    followUpDelayText: 'In 4 days',
    clientResponse: 'Under Review',
    assignedTo: 'Ramesh Thapa',
    remarks: 'Need itinerary module',
    leadSource: 'Google Maps',
    productsInterestedText: 'Ecommerce Website'
  },
  {
    id: 'W-010',
    businessName: 'Nepal School Of Music',
    city: 'Balkhu, Kathmandu',
    contactPerson: 'Sabin Bhattarai',
    contactRole: 'Director',
    phone: '9810099880',
    email: 'sabin@nepalmusic.com',
    category: 'Education',
    websiteStatus: 'Business Website',
    suggestedPitch: 'Add courses, events and inquiry form.',
    packageOffered: 'Business Website\n(NPR 19,999)',
    leadPriority: 'Warm',
    followUpStatus: 'Proposal Sent',
    nextFollowUpDate: '25 May 2025',
    followUpDelayText: 'In 7 days',
    clientResponse: 'Interested',
    assignedTo: 'Anita Sharma',
    remarks: 'Needs online admission form',
    leadSource: 'Website',
    productsInterestedText: 'Business Website'
  }
];

export const initialSoftwareLeads: Lead[] = [
  {
    id: 'S-001',
    businessName: 'Pokhara Traders Pvt. Ltd.',
    city: 'Pokhara, Gandaki',
    contactPerson: 'Prakash Adhikari',
    contactRole: 'Director',
    phone: '9845123456',
    email: 'prakash@pokharatraders.com',
    category: 'Trading',
    productsInterestedText: 'Inventory, Accounting',
    leadSource: 'Google Maps',
    leadPriority: 'Hot',
    followUpStatus: 'Follow-up Required',
    nextFollowUpDate: '20 May 2025',
    followUpDelayText: 'In 2 days',
    assignedTo: 'Anita Sharma'
  },
  {
    id: 'S-002',
    businessName: 'Birat Agro Suppliers',
    city: 'Biratnagar, Koshi',
    contactPerson: 'Niraj Yadav',
    contactRole: 'Proprietor',
    phone: '9862012345',
    email: 'niraj@biratagro.com',
    category: 'Agriculture',
    productsInterestedText: 'Inventory, Purchase',
    leadSource: 'Referral',
    leadPriority: 'Hot',
    followUpStatus: 'Proposal Sent',
    nextFollowUpDate: '19 May 2025',
    followUpDelayText: 'Tomorrow',
    assignedTo: 'Pooja Mahat'
  },
  {
    id: 'S-003',
    businessName: 'Everest Construction Pvt. Ltd.',
    city: 'Kathmandu, Bagmati',
    contactPerson: 'Sandeep Khatri',
    contactRole: 'Project Manager',
    phone: '9859876543',
    email: 'sandeep@everestconst.com',
    category: 'Construction',
    productsInterestedText: 'Accounting, HRMS',
    leadSource: 'Google Maps',
    leadPriority: 'Warm',
    followUpStatus: 'Interested',
    nextFollowUpDate: '22 May 2025',
    followUpDelayText: 'In 4 days',
    assignedTo: 'Anita Sharma'
  },
  {
    id: 'S-004',
    businessName: 'Smart Retail Mart',
    city: 'Butwal, Lumbini',
    contactPerson: 'Bikash Timilsina',
    contactRole: 'Owner',
    phone: '9865567788',
    email: 'bikash@smartretail.com',
    category: 'Retail',
    productsInterestedText: 'POS, Inventory',
    leadSource: 'Walk-in',
    leadPriority: 'Warm',
    followUpStatus: 'Not Contacted',
    nextFollowUpDate: '26 May 2025',
    followUpDelayText: 'In 8 days',
    assignedTo: 'Bikram Raut'
  }
];

export const initialSocialMediaLeads: Lead[] = [
  {
    id: 'SM-001',
    businessName: "Kathmandu Valley Bakery",
    city: "New Baneshwor, Kathmandu",
    contactPerson: "Niranjan Karki",
    contactRole: "General Manager",
    phone: "9841223344",
    email: "niranjan@ktmbakery.com",
    category: "Retail",
    leadSource: "Facebook",
    leadPriority: "Hot",
    followUpStatus: "Follow-up Required",
    nextFollowUpDate: "20 May 2025",
    followUpDelayText: "Today",
    assignedTo: "Sujan Karki",
    remarks: "Needs automated pricing and billing software.",
    platform: "Facebook",
    productsInterestedText: "POS, Billing Software"
  },
  {
    id: 'SM-002',
    businessName: "Pokhara Heights Retreat",
    city: "Lakeside, Pokhara",
    contactPerson: "Aditi Thapa",
    contactRole: "Front Office head",
    phone: "9856011223",
    email: "aditi@pokharaheights.com",
    category: "Hospitality",
    leadSource: "Instagram",
    leadPriority: "Warm",
    followUpStatus: "Demo Scheduled",
    nextFollowUpDate: "21 May 2025",
    followUpDelayText: "In 3 days",
    assignedTo: "Anita Sharma",
    remarks: "Inquired about a booking custom system from our latest reel advertisement.",
    platform: "Instagram",
    productsInterestedText: "Clinic/Hotel Booking System"
  },
  {
    id: 'SM-003',
    businessName: "The Fitness Grid",
    city: "Lalitpur, Lalitpur",
    contactPerson: "Raju Shrestha",
    contactRole: "Owner",
    phone: "9803344556",
    email: "raju@thefitnessgrid.com",
    category: "Retail",
    leadSource: "Facebook",
    leadPriority: "Warm",
    followUpStatus: "Proposal Sent",
    nextFollowUpDate: "22 May 2025",
    followUpDelayText: "In 4 days",
    assignedTo: "Ramesh Thapa",
    remarks: "Direct inquiry about POS invoice modules from our link description.",
    platform: "Instagram",
    productsInterestedText: "Billing Software, POS"
  },
  {
    id: 'SM-004',
    businessName: "Chitwan Wildlife Tours",
    city: "Sauraha, Chitwan",
    contactPerson: "Pramod Giri",
    contactRole: "Managing Director",
    phone: "9845099887",
    email: "pramod@chitwantours.com",
    category: "Hospitality",
    leadSource: "Facebook",
    leadPriority: "Cold",
    followUpStatus: "Call Attempted",
    nextFollowUpDate: "23 May 2025",
    followUpDelayText: "In 5 days",
    assignedTo: "Pooja Mahat",
    remarks: "Inquired about lead capture forms under our sponsor story.",
    platform: "Facebook",
    productsInterestedText: "Website Design Starter"
  },
  {
    id: 'SM-005',
    businessName: "Apex IT Academy",
    city: "Lagankhel, Lalitpur",
    contactPerson: "Karuna Shakya",
    contactRole: "Admissions Lead",
    phone: "9812455667",
    email: "karuna@apexit.edu.np",
    category: "Education",
    leadSource: "Instagram",
    leadPriority: "Hot",
    followUpStatus: "Follow-up Required",
    nextFollowUpDate: "20 May 2025",
    followUpDelayText: "Today",
    assignedTo: "Bikram Raut",
    remarks: "Commented asking for school management demo presentation.",
    platform: "Facebook",
    productsInterestedText: "School Software"
  }
];

export const initialDemos: Demo[] = [
  {
    id: 'D-001',
    clientName: 'Fashion Hub',
    contactPerson: 'Ramesh Shrestha',
    leadId: 'S-001',
    productService: 'Ecommerce System',
    demoMode: 'Online',
    demoDate: '2026-05-30',
    demoTime: '10:30 AM - 11:00 AM',
    demoStatus: 'Confirmed',
    assignedTo: 'Sujan Karki',
    outcomeNextStep: 'Demo today, prepare tailored ecommerce pricing proposal',
    meetingLink: 'https://meet.google.com/abc-defg-hij',
    demoAgenda: 'Product overview, Features, Pricing, Q&A',
    remarksNotes: 'Client is looking for ecommerce solution integrated with core billing and regional SMS integration.'
  },
  {
    id: 'D-002',
    clientName: 'New Shree Hardware',
    contactPerson: 'Dipak Adhikari',
    leadId: 'S-005',
    productService: 'Ecommerce System',
    demoMode: 'Online',
    demoDate: '2026-05-31',
    demoTime: '11:30 AM - 12:00 PM',
    demoStatus: 'Scheduled',
    assignedTo: 'Anita Sharma',
    outcomeNextStep: 'Send reminder, confirm attendance',
    meetingLink: 'https://meet.google.com/xyz-wdqr-mno',
    demoAgenda: 'Inventory control, stock reports, automated barcode scanning demo'
  },
  {
    id: 'D-003',
    clientName: 'ABC Law Associates',
    contactPerson: 'Adv. Bipin Neupane',
    leadId: 'S-006',
    productService: 'Court Management System',
    demoMode: 'Online',
    demoDate: '2026-06-01',
    demoTime: '02:00 PM - 02:45 PM',
    demoStatus: 'Scheduled',
    assignedTo: 'Bikram Raut',
    outcomeNextStep: 'Share legal firm database case studies',
    meetingLink: 'https://meet.google.com/pqr-stuv-wxy',
    demoAgenda: 'Workflow dashboard, client folders, hearing calendar and notifications'
  },
  {
    id: 'D-004',
    clientName: 'Green Valley Hospital',
    contactPerson: 'Dr. Suman Kafle',
    leadId: 'S-007',
    productService: 'eHMIS / NHMIS',
    demoMode: 'On-site',
    demoDate: '2026-05-29',
    demoTime: '03:00 PM - 04:00 PM',
    demoStatus: 'Completed',
    assignedTo: 'Pooja Mahat',
    outcomeNextStep: 'Prepare hospital implementation draft quotation',
    demoAgenda: 'OPD management, pathology bills, patient intake form flow'
  }
];

export const initialProposals: Proposal[] = [
  {
    id: 'P-001',
    proposalNo: 'PR-2025-0085',
    client: 'Fashion Hub',
    project: 'Website Development',
    productInterest: 'Ecommerce Web Store',
    amount: 85000,
    status: 'Accepted',
    sentOn: '2025-05-16',
    validUntil: '2025-05-30',
    owner: 'Sujan Karki',
    lastActivity: 'Accepted 17 May 2025',
    items: [
      { id: '1', name: 'Ecommerce Custom Module Web', quantity: 1, price: 65000, tax: 13, discount: 5000 },
      { id: '2', name: 'Cloud Storage & Maintenance (1 Yr)', quantity: 1, price: 20000, tax: 13, discount: 0 }
    ],
    notes: 'Client accepted proposal. Awaiting initial 50% database installment deposit.',
    history: [
      { date: '10 May 2025 11:30 AM', action: 'Created & Sent', user: 'Sujan Karki' },
      { date: '11 May 2025 02:15 PM', action: 'Viewed', user: 'Client' },
      { date: '17 May 2025 04:10 PM', action: 'Accepted', user: 'Client' }
    ],
    files: [
      { name: 'Ecommerce_Proposal_FashionHub.pdf', size: '2.4 MB', url: '#' },
      { name: 'Requirement_Sheet_FashionHub.xlsx', size: '412 KB', url: '#' }
    ]
  },
  {
    id: 'P-002',
    proposalNo: 'PR-2025-0084',
    client: 'New Shree Hardware',
    project: 'Inventory System',
    productInterest: 'Inventory Management',
    amount: 125000,
    status: 'Viewed',
    sentOn: '2025-05-15',
    validUntil: '2025-05-29',
    owner: 'Anita Sharma',
    lastActivity: 'Viewed 16 May 2025',
    items: [
      { id: '1', name: 'Inventory Core System license', quantity: 1, price: 110000, tax: 13, discount: 0 },
      { id: '2', name: 'Deployment and Database setup', quantity: 1, price: 15000, tax: 13, discount: 0 }
    ],
    history: [
      { date: '15 May 2025 10:00 AM', action: 'Sent to email', user: 'Anita Sharma' },
      { date: '16 May 2025 09:30 AM', action: 'Viewed by Contact', user: 'Client' }
    ]
  },
  {
    id: 'P-003',
    proposalNo: 'PR-2025-0083',
    client: 'Green Valley Hospital',
    project: 'eHMIS Implementation',
    productInterest: 'Health Records Module',
    amount: 240000,
    status: 'Sent',
    sentOn: '2025-05-14',
    validUntil: '2025-05-28',
    owner: 'Ramesh Thapa',
    lastActivity: 'Sent 14 May 2025',
    items: [
      { id: '1', name: 'eHMIS core engine backend', quantity: 1, price: 212000, tax: 13, discount: 0 },
      { id: '2', name: 'Cloud synchronization API lic', quantity: 1, price: 28000, tax: 13, discount: 0 }
    ],
    history: [
      { date: '14 May 2025 04:00 PM', action: 'Sent by ramesh', user: 'Ramesh Thapa' }
    ]
  },
  {
    id: 'P-004',
    proposalNo: 'PR-2025-0082',
    client: 'ABC Law Associates',
    project: 'Case Management System',
    productInterest: 'Legal DMS ERP',
    amount: 180000,
    status: 'Draft',
    sentOn: '-',
    validUntil: '-',
    owner: 'Dipak Adhikari',
    lastActivity: 'Draft 13 May 2025',
    items: [
      { id: '1', name: 'Legal Case flow manager module', quantity: 1, price: 159000, tax: 13, discount: 0 },
      { id: '2', name: 'DMS integrations plugins', quantity: 1, price: 21000, tax: 13, discount: 0 }
    ],
    history: [
      { date: '13 May 2025 02:00 PM', action: 'Created Initial Draft', user: 'Dipak Adhikari' }
    ]
  },
  {
    id: 'P-005',
    proposalNo: 'PR-2025-0081',
    client: 'City Mart',
    project: 'POS & Billing System',
    productInterest: 'Omnichannel POS ERP',
    amount: 95000,
    status: 'Rejected',
    sentOn: '2025-05-12',
    validUntil: '2025-05-26',
    owner: 'Sujan Karki',
    lastActivity: 'Rejected 13 May 2025',
    items: [
      { id: '1', name: 'Retail POS Client Software License', quantity: 1, price: 84000, tax: 13, discount: 0 },
      { id: '2', name: 'Thermal Printers and scan api setup', quantity: 1, price: 11000, tax: 13, discount: 0 }
    ],
    history: [
      { date: '12 May 2025 11:00 AM', action: 'Dispatched to mart manager', user: 'Sujan Karki' },
      { date: '13 May 2025 03:00 PM', action: 'Rejected due to budget constraints', user: 'Client' }
    ]
  },
  {
    id: 'P-006',
    proposalNo: 'PR-2025-0080',
    client: 'Bright Future School',
    project: 'School Management',
    productInterest: 'eSchool Solutions Suite',
    amount: 110000,
    status: 'Viewed',
    sentOn: '2025-05-10',
    validUntil: '2025-05-24',
    owner: 'Anita Sharma',
    lastActivity: 'Viewed 12 May 2025',
    items: [
      { id: '1', name: 'SMS and grading automation portal', quantity: 1, price: 97000, tax: 13, discount: 0 },
      { id: '2', name: 'Annual support license basic', quantity: 1, price: 13000, tax: 13, discount: 0 }
    ],
    history: [
      { date: '10 May 2025 09:30 AM', action: 'Dispatched Proposal PDF', user: 'Anita Sharma' },
      { date: '12 May 2025 04:00 PM', action: 'Viewed by Principal computer', user: 'Client' }
    ]
  },
  {
    id: 'P-007',
    proposalNo: 'PR-2025-0079',
    client: 'Himalayan Traders',
    project: 'Mobile App Development',
    productInterest: 'React Native IOS and Android',
    amount: 160000,
    status: 'Expired',
    sentOn: '2025-05-08',
    validUntil: '2025-05-18',
    owner: 'Ramesh Thapa',
    lastActivity: 'Expired 18 May 2025',
    items: [
      { id: '1', name: 'Dynamic mobile catalogue development', quantity: 1, price: 141000, tax: 13, discount: 0 },
      { id: '2', name: 'App store submission setups', quantity: 1, price: 19000, tax: 13, discount: 0 }
    ],
    history: [
      { date: '08 May 2025 10:00 AM', action: 'Draft proposal dispatched', user: 'Ramesh Thapa' },
      { date: '18 May 2025 12:00 AM', action: 'Validity Period Expired', user: 'System' }
    ]
  },
  {
    id: 'P-008',
    proposalNo: 'PR-2025-0078',
    client: 'Om Steel Suppliers',
    project: 'Vendor Management',
    productInterest: 'Supply Chain Tracker',
    amount: 70000,
    status: 'Sent',
    sentOn: '2025-05-05',
    validUntil: '2025-05-19',
    owner: 'Dipak Adhikari',
    lastActivity: 'Sent 05 May 2025',
    items: [
      { id: '1', name: 'Vendor Ledger database manager', quantity: 1, price: 61000, tax: 13, discount: 0 },
      { id: '2', name: 'API custom gateway and tokens', quantity: 1, price: 9000, tax: 13, discount: 0 }
    ],
    history: [
      { date: '05 May 2025 02:00 PM', action: 'Dispatched via Admin CRM console', user: 'Dipak Adhikari' }
    ]
  }
];

export const initialClients: Client[] = [
  {
    id: 'C-001',
    clientName: 'SoftTech Solutions Pvt. Ltd.',
    companyName: 'SoftTech Solutions',
    contactPerson: 'Ramesh Shrestha',
    phone: '9811234567',
    email: 'ramesh@softtech.com',
    address: 'Dillibazar, Kathmandu, Nepal',
    clientGroup: 'IT & Software',
    status: 'Active',
    joinedOn: '2024-05-10',
    panNumber: '606123456',
    notes: 'Important strategic client for CRM cloud suite and customized corporate portal setup.',
    totalProjects: 3,
    totalInvoices: 12,
    totalPaid: 1450000,
    totalOutstanding: 225000
  },
  {
    id: 'C-002',
    clientName: 'Green Valley Hospital',
    companyName: 'Green Valley Hospital',
    contactPerson: 'Dr. Suman Kafle',
    phone: '9851122334',
    email: 'info@greenvalley.com',
    address: 'Chitwan, Bagmati, Nepal',
    clientGroup: 'Healthcare',
    status: 'Active',
    joinedOn: '2024-05-12',
    panNumber: '302455612',
    totalProjects: 2,
    totalInvoices: 4,
    totalPaid: 800000,
    totalOutstanding: 450000
  },
  {
    id: 'C-003',
    clientName: 'ABC Trading Co.',
    companyName: 'ABC Trading',
    contactPerson: 'Anita Sharma',
    phone: '9802345678',
    email: 'anita@abctrading.com',
    address: 'Biratnagar, Koshi, Nepal',
    clientGroup: 'Trading',
    status: 'Active',
    joinedOn: '2024-05-15',
    panNumber: '504122394',
    totalProjects: 1,
    totalInvoices: 2,
    totalPaid: 450000,
    totalOutstanding: 0
  }
];

export const initialCampaigns: Campaign[] = [
  {
    id: 'CP-01',
    campaignName: 'Summer Offer 2026',
    type: 'Promotional',
    channel: 'Email',
    targetAudience: 'Website Leads',
    sent: 12456,
    responses: 2345,
    openRate: 32.5,
    clickRate: 12.4,
    status: 'Completed',
    startDate: '2026-05-10',
    endDate: '2026-05-16',
    subject: 'Summer Sale is Here! Get 50% OFF',
    preheader: "Don't miss out on our biggest sale of the year. Build your web app today.",
    analytics: {
      opened: 4045,
      clicked: 1542,
      bounced: 256,
      unsubscribed: 189
    }
  },
  {
    id: 'CP-02',
    campaignName: 'New Feature Announcement',
    type: 'Informational',
    channel: 'Email',
    targetAudience: 'Existing Clients',
    sent: 8932,
    responses: 1256,
    openRate: 28.6,
    clickRate: 8.4,
    status: 'Completed',
    startDate: '2026-05-10',
    endDate: '2026-05-15',
    subject: 'Introducing our new analytical dashboards and offline state management!',
    analytics: {
      opened: 2555,
      clicked: 750,
      bounced: 110,
      unsubscribed: 45
    }
  },
  {
    id: 'CP-03',
    campaignName: 'Webinar Invitation - CRM Secrets',
    type: 'Event',
    channel: 'Email',
    targetAudience: 'All Leads',
    sent: 15230,
    responses: 2408,
    openRate: 34.2,
    clickRate: 15.8,
    status: 'Completed',
    startDate: '2026-05-05',
    endDate: '2026-05-16',
    subject: 'Free Class: 5 ways to double your lead conversions using intelligent CRM'
  }
];

export const initialInvoices: PaymentInvoice[] = [
  {
    id: 'INV-001',
    invoiceNo: 'INV-2026-048',
    client: 'SoftTech Solutions',
    project: 'Nagarik CRM Development',
    invoiceDate: '2026-05-10',
    dueDate: '2026-06-20',
    amount: 1250000,
    paidAmount: 1250000,
    discount: 0,
    tax: 143805,
    status: 'Paid',
    paymentMethod: 'Bank Transfer',
    paidOn: '2026-05-15',
    transactionId: 'NMB20250515123456',
    notes: 'Payment received via bank transfer setup.'
  },
  {
    id: 'INV-002',
    invoiceNo: 'INV-2026-047',
    client: 'ABC Trading Co.',
    project: 'E-commerce Website',
    invoiceDate: '2026-05-15',
    dueDate: '2026-06-30',
    amount: 875000,
    paidAmount: 875000,
    discount: 10000,
    tax: 113750,
    status: 'Paid',
    paymentMethod: 'Khalti',
    paidOn: '2026-05-16'
  },
  {
    id: 'INV-003',
    invoiceNo: 'INV-2026-046',
    client: 'Himalayan Bank Ltd.',
    project: 'Inventory Management',
    invoiceDate: '2026-04-01',
    dueDate: '2026-05-10',
    amount: 920000,
    paidAmount: 920000,
    discount: 0,
    tax: 119600,
    status: 'Paid',
    paymentMethod: 'Bank Transfer',
    paidOn: '2026-05-05'
  },
  {
    id: 'INV-004',
    invoiceNo: 'INV-2026-045',
    client: 'Bright Future School',
    project: 'Corporate Website Redesign',
    invoiceDate: '2026-04-05',
    dueDate: '2026-05-15',
    amount: 450000,
    paidAmount: 450000,
    discount: 5000,
    tax: 58500,
    status: 'Paid',
    paymentMethod: 'eSewa',
    paidOn: '2026-05-15'
  },
  {
    id: 'INV-005',
    invoiceNo: 'INV-2026-044',
    client: 'Green Valley Hospital',
    project: 'HRM System Development',
    invoiceDate: '2026-05-20',
    dueDate: '2026-07-15',
    amount: 1000000,
    paidAmount: 300000,
    discount: 0,
    tax: 130000,
    status: 'Partial',
    paymentMethod: 'Bank Transfer'
  }
];

export const initialPackages: ProductPackage[] = [
  {
    id: 'PKG-001',
    name: 'Nagarik CRM',
    category: 'Software',
    type: 'SaaS',
    skuCode: 'SW-CRM-001',
    sellingPrice: 45000,
    billingFrequency: 'year',
    status: 'Active',
    createdOn: '2025-05-10',
    description: 'A complete CRM solution to manage leads, clients, sales pipeline, and customer interactions.',
    features: ['Leads pipeline', 'Client analytics', 'Invoices Tracker', 'Multi-channel Campaigns', 'Task Calendar']
  },
  {
    id: 'PKG-002',
    name: 'Nagarik Accounting',
    category: 'Software',
    type: 'SaaS',
    skuCode: 'SW-ACC-002',
    sellingPrice: 35000,
    billingFrequency: 'year',
    status: 'Active',
    createdOn: '2025-05-12',
    description: 'Smart accounting and billing software with local taxation support (VAT/PAN).',
    features: ['Invoices generation', 'Tax logs VAT 13%', 'Khalti/eSewa plugins', 'Detailed Profit & Loss']
  },
  {
    id: 'PKG-003',
    name: 'Nagarik HRM',
    category: 'Software',
    type: 'SaaS',
    skuCode: 'SW-HRM-003',
    sellingPrice: 40000,
    billingFrequency: 'year',
    status: 'Active',
    createdOn: '2025-05-14',
    description: 'Complete HR system for managing attendance, leave, dynamic salary slips, and performance scores.',
    features: ['Attendance Clocking', 'Leave Approvals', 'Payslips Generator', 'NPR Taxation Settings']
  },
  {
    id: 'PKG-004',
    name: 'Nagarik Project Management',
    category: 'Software',
    type: 'SaaS',
    skuCode: 'SW-PM-004',
    sellingPrice: 30000,
    billingFrequency: 'year',
    status: 'Active',
    createdOn: '2025-05-16',
    description: 'Team planning platform with Gantt views, tasks scheduler, and time log tracker matrices.',
    features: ['Gantt Chart Workspace', 'Time Log Tracker', 'Sprint Board', 'Client Shared View']
  },
  {
    id: 'PKG-005',
    name: 'Nagarik Helpdesk',
    category: 'Software',
    type: 'SaaS',
    skuCode: 'SW-HELP-005',
    sellingPrice: 25000,
    billingFrequency: 'year',
    status: 'Active',
    createdOn: '2025-05-18',
    description: 'Customer ticket support Desk with automated response channels and feedback surveys.',
    features: ['Inbound Email Routing', 'SLA Escalate Alert', 'Knowledge Desk CMS', 'Rating Poll Client']
  },
  {
    id: 'PKG-006',
    name: 'Nagarik Inventory',
    category: 'Software',
    type: 'SaaS',
    skuCode: 'SW-INV-006',
    sellingPrice: 32000,
    billingFrequency: 'year',
    status: 'Inactive',
    createdOn: '2025-05-19',
    description: 'Stock purchase orders flow with barcode scanners integration and multi-warehouse indexes.',
    features: ['Multi-warehouse Stock', 'Reorder Alerts', 'Barcode Scanner API', 'Purchase Orders PDF']
  },
  {
    id: 'PKG-007',
    name: 'Business Website Basic',
    category: 'Websites',
    type: 'Package',
    skuCode: 'WEB-BASIC-001',
    sellingPrice: 15000,
    billingFrequency: 'one-time',
    status: 'Active',
    createdOn: '2025-05-20',
    description: 'Responsive template website suited for general company presentations and service catalogs.',
    features: ['About us, Services Pages', 'Contact form setup', 'Mobile responsive theme', '1 Year free setup domain']
  },
  {
    id: 'PKG-008',
    name: 'Business Website Standard',
    category: 'Websites',
    type: 'Package',
    skuCode: 'WEB-STD-002',
    sellingPrice: 35000,
    billingFrequency: 'one-time',
    status: 'Active',
    createdOn: '2025-05-21',
    description: 'Dynamic responsive corporate website with blog modules, gallery, and contact management.',
    features: ['CMS blog post console', 'Interactive map embeds', 'SSL security installation', 'Domain email creation']
  },
  {
    id: 'PKG-009',
    name: 'E-commerce Website',
    category: 'Websites',
    type: 'Package',
    skuCode: 'WEB-ECO-003',
    sellingPrice: 65000,
    billingFrequency: 'one-time',
    status: 'Active',
    createdOn: '2025-05-22',
    description: 'Store setup with dynamic cart checkouts, digital payment Gateways integrations, and stock reports.',
    features: ['Digital Checkout engine', 'Fonepay API connection', 'Stock reports dashboard', 'Automated email invoices']
  },
  {
    id: 'PKG-010',
    name: 'Portfolio Website',
    category: 'Websites',
    type: 'Package',
    skuCode: 'WEB-PORT-004',
    sellingPrice: 12000,
    billingFrequency: 'one-time',
    status: 'Active',
    createdOn: '2025-05-23',
    description: 'Aesthetic responsive personal portfolio layout for creative freelancers and project displays.',
    features: ['Visual Grid Gallery', 'Bio / resume presentation', 'Inquiry forms integration', 'Aesthetic typography options']
  }
];
